version: 2
updates:
  # Rust dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "00:00"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "rust"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    # Group all dependencies together for easier review
    groups:
      dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Ignore major versions to prevent breaking changes
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]