version: "3.8"

services:
  # Our mqttv5 broker (primary service)
  mqttv5-broker:
    build:
      context: .
      dockerfile: Dockerfile.broker
    container_name: mqttv5-test-broker
    ports:
      - "1883:1883"
      - "8883:8883"
    volumes:
      - ./test_certs:/app/certs:ro
      - mqttv5-data:/app/data
    command: ["mqttv5", "broker", "--host", "0.0.0.0:1883"]
    environment:
      - RUST_LOG=mqtt_v5=info
    healthcheck:
      test: ["CMD", "mqttv5", "pub", "--host", "localhost", "--topic", "health/check", "--message", "ping", "--non-interactive", "--qos", "0"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  # Our mqttv5 broker with TLS (secondary service for TLS testing)  
  mqttv5-broker-tls:
    build:
      context: .
      dockerfile: Dockerfile.broker
    container_name: mqttv5-test-broker-tls
    ports:
      - "8884:8883"
    volumes:
      - ./test_certs:/app/certs:ro
      - mqttv5-tls-data:/app/data
    command: ["mqttv5", "broker", "--host", "0.0.0.0:8883"]
    environment:
      - RUST_LOG=mqtt_v5=info
    healthcheck:
      test: ["CMD", "mqttv5", "pub", "--host", "localhost", "--port", "8883", "--topic", "health/check", "--message", "ping", "--non-interactive", "--qos", "0"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  # Keep mosquitto for comparison/fallback (optional)
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mqtt-test-broker-mosquitto  
    ports:
      - "1885:1883"  # Different port to avoid conflict
    volumes:
      - ./comparative_benchmarks/test_configs/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./test_certs:/mosquitto/certs:ro
      - mosquitto-data:/mosquitto/data
    command: mosquitto -c /mosquitto/config/mosquitto.conf
    profiles: ["comparison"]  # Only start when explicitly requested

volumes:
  mqttv5-data:
  mqttv5-tls-data:
  mosquitto-data:
