name: Dependencies

on:
  schedule:
    # Run at 00:00 on Monday
    - cron: '0 0 * * 1'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  update:
    name: Update Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Generate test certificates
        run: |
          chmod +x scripts/generate_test_certs.sh
          ./scripts/generate_test_certs.sh

      - name: Update dependencies
        run: cargo update

      - name: Check if updates work
        run: |
          cargo check --all-features
          cargo test --all-features
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update dependencies"
          title: "Automated dependency updates"
          body: |
            This PR updates the dependencies to their latest versions.
            
            Please review the changes and ensure all tests pass before merging.
          branch: automated-dependency-updates
          delete-branch: true